### PR TITLE
add yocto support for Rock-3a-rk3568

### PR DESCRIPTION
**Pull request by thanhlev**
- Success to build console and desktop image
- Verified on rock3a hardware

### CODE REVIEW

**Comment by RadxaStephen** [comment]
Good news. Glad to hear that you fix the missing atf.

1.https://github.com/radxa/meta-radxa/pull/29/commits/b6bc43d86572dcb7c96e197208ad07223c5f5334

Please change "rk3268" to "rk3568" since the SoC of ROCK 3A is RK3568.

2.Would you please change the name from rock3a to rock-3a in the patches?

Like rk3568-rock-3a, rock-3a, etc.

**Comment by thanhlev** [comment]
> Good news. Glad to hear that you fix the missing atf.
> 
> 1.[b6bc43d](https://github.com/radxa/meta-radxa/commit/b6bc43d86572dcb7c96e197208ad07223c5f5334)
> 
> Please change "rk3268" to "rk3568" since the SoC of ROCK 3A is RK3568.
> 
> 2.Would you please change the name from rock3a to rock-3a in the patches?
> 
> Like rk3568-rock-3a, rock-3a, etc.

Hi @RadxaStephen , I have updated according to your comment, please take a look

**Comment by RadxaStephen** [comment]
Hello, 

https://github.com/quangthanh010290/meta-radxa/commit/6547e9a96d8eb2782d895b989b13f6d8cc04fc21

This commit title is not right.

Please use "rename rock3a to rock-3a-rk3568" instead of "rename rock3a to rock-3a-rk3288"

**Comment by thanhlev** [comment]
hi @RadxaStephen , 
I had renamed and squashed the commit, please take a look.

**Comment by RadxaStephen** [comment]
Thanks.

I have two more questions.

The first one is ROOT UUID. 

 I notice that you use a different ROOT_UUID for rk3568. Why?

```
if [ "${SOC_FAMILY}" = "rk3568" ]; then
		ROOT_UUID="614e0000-0000-4b53-8000-1d28000054a9"
```

ROOT_UUID is specified for rootfs device. I think we can use one ROOT_UUID. What do you think?

And the second one is the U-Boot ROCK 3A dts and defconfig name.

To sync with Mainline Linux. We have changed the name. Like

```
rk3568-rock-3a.dts
rock-3a-rk3568_defconfig
```

See these commits

* https://github.com/radxa/u-boot/commit/41ffd0087708e3381e7e166c4ca646f31cd9e097
* https://github.com/radxa/kernel/commit/67a0c0ce87a07769ea7afd4a0978a0f22c76f8ce

**Comment by thanhlev** [comment]
Hi @RadxaStephen 
1. 
> I notice that you use a different ROOT_UUID for rk3568. Why?

I follow setup from bsp: [mk-image.sh](https://github.com/radxa/build/blob/b47fa57b1b6a4a6347cc0cfb8d7af96015e1487d/mk-image.sh), but it seems the master branch is updated, I will try to use the configuration from master branch.

2. 

> To sync with Mainline Linux. We have changed the name. Like

I will sync with mainline and test.

**Comment by thanhlev** [comment]
Hi @RadxaStephen 
- I have updated according to your comments and verified on target, please review again
- This is console log
```
root@rock-3a-rk3568:~# cat /proc/version 
Linux version 4.19.193 (oe-user@oe-host) (gcc version 9.3.0 (GCC), GNU ld (GNU Binutils) 2.34.0.2020
0220) #1 SMP Thu Aug 4 02:15:52 UTC 202
```

**Comment by RadxaStephen** [comment]
@quangthanh010290  Very appreciated. Thank you.

**Pull request merged**
